version: '2'
services:
  amazon-lib-list:
    build: .
    container_name: 'amazon-lib-list'
    tty: true
    volumes:
      - './src:/data/src'
      - './tests:/data/tests'
      - './work:/data/work'
      - './config:/data/config'
      - './log:/data/log'
    working_dir: '/data/src'
